// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vacation.Data;

#nullable disable

namespace Vacation.Migrations
{
    [DbContext(typeof(VacationDbContext))]
    [Migration("20230422201053_Labb1WebbApp2")]
    partial class Labb1WebbApp2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vacation.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Vacation.Models.VacationList", b =>
                {
                    b.Property<int>("VacationListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacationListId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_VacationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VacCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("VacationListId");

                    b.HasIndex("FK_EmployeeId");

                    b.HasIndex("FK_VacationTypeId");

                    b.ToTable("VacationLists");
                });

            modelBuilder.Entity("Vacation.Models.VacationType", b =>
                {
                    b.Property<int>("VacationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacationTypeId"));

                    b.Property<string>("VacationTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VacationTypeId");

                    b.ToTable("VacationTypes");
                });

            modelBuilder.Entity("Vacation.Models.VacationList", b =>
                {
                    b.HasOne("Vacation.Models.Employee", "Employees")
                        .WithMany("VacationLists")
                        .HasForeignKey("FK_EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vacation.Models.VacationType", "VacationTypes")
                        .WithMany("VacationLists")
                        .HasForeignKey("FK_VacationTypeId");

                    b.Navigation("Employees");

                    b.Navigation("VacationTypes");
                });

            modelBuilder.Entity("Vacation.Models.Employee", b =>
                {
                    b.Navigation("VacationLists");
                });

            modelBuilder.Entity("Vacation.Models.VacationType", b =>
                {
                    b.Navigation("VacationLists");
                });
#pragma warning restore 612, 618
        }
    }
}
